plugin:
  has_options: false
  icon: res_file.png    

  resources:
    - class: Innova\MediaResourceBundle\Entity\MediaResource
      name: innova_media_resource
      is_exportable: false
      icon: res_file.png
      actions:
        - name: administrate
          menu_name: innova_media_resource_administrate
