parameters:       
    # Listeners
    innova_media_resource.listener.media_resource.class:    Innova\MediaResourceBundle\EventListener\Resource\MediaResourceListener
    
    # Form Types
    innova_media_resource.form.type.media_resource.class:   Innova\MediaResourceBundle\Form\Type\MediaResourceType
    
    # Managers
    innova_media_resource.manager.playlist_region.class:    Innova\MediaResourceBundle\Manager\PlaylistRegionManager
    innova_media_resource.manager.playlist.class:           Innova\MediaResourceBundle\Manager\PlaylistManager