parameters:       
    # Listeners
    innova_media_resource.listener.media_resource.class:    Innova\MediaResourceBundle\EventListener\Resource\MediaResourceListener
    
    # Form Types
    innova_media_resource.form.type.media_resource.class:   Innova\MediaResourceBundle\Form\Type\MediaResourceType
    
    # Parameters  
    # for upload
    innova_media_resource.param.upload_files_directory:     "%kernel.root_dir%/../innovamediaresourcefiles"
    # for display
    innova_media_resource.param.read_files_directory:       "/../../innovamediaresourcefiles"
