innova_media_resource:
    resource: "@InnovaMediaResourceBundle/Controller/MediaResourceController.php"
    prefix:   /
    type: annotation
innova_playlist:
    resource: "@InnovaMediaResourceBundle/Controller/PlaylistController.php"
    prefix: /playlists
    type: annotation
