services: 
    # Media resource main controller
    innova_media_resource.controller.media_resource:
        class: %innova_media_resource.controller.media_resource.class%
        arguments:
            mediaResourceManager: @innova_media_resource.manager.media_resource