services:
    innova_media_resource.manager.media_resource:
        class: Innova\MediaResourceBundle\Manager\MediaResourceManager 
        arguments:
            entityManager:  @doctrine.orm.entity_manager
            translator:     @translator
    innova_media_resource.manager.media_resource_media:
        class: Innova\MediaResourceBundle\Manager\MediaManager 
        arguments:
            entityManager:  @doctrine.orm.entity_manager
    innova_media_resource.manager.media_resource_region:
        class: Innova\MediaResourceBundle\Manager\RegionManager 
        arguments:
            entityManager:  @doctrine.orm.entity_manager
            translator:     @translator
            playlistRegionManager: @innova_media_resource.manager.playlist_region
    innova_media_resource.manager.playlist:
        class: Innova\MediaResourceBundle\Manager\PlaylistManager 
        arguments:
            entityManager:  @doctrine.orm.entity_manager
            translator:     @translator
    innova_media_resource.manager.playlist_region:
        class: Innova\MediaResourceBundle\Manager\PlaylistRegionManager 
        arguments:
            entityManager:  @doctrine.orm.entity_manager
            translator:     @translator
            plManager:      @innova_media_resource.manager.playlist
            
