services:
    innova_media_resource.manager.media_resource:
        class: Innova\MediaResourceBundle\Manager\MediaResourceManager 
        arguments:
            entityManager:  @doctrine.orm.entity_manager
            translator:     @translator
            fileDir:        %innova_media_resource.param.files_directory%
    innova_media_resource.manager.media_resource_media:
        class: Innova\MediaResourceBundle\Manager\MediaManager 
        arguments:
            entityManager:  @doctrine.orm.entity_manager
            fileDirName:    %innova_media_resource.param.files_directory_name%
    innova_media_resource.manager.media_resource_region:
        class: Innova\MediaResourceBundle\Manager\RegionManager 
        arguments:
            entityManager:  @doctrine.orm.entity_manager
            translator:     @translator
    innova_media_resource.manager.media_resource_region_config:
        class: Innova\MediaResourceBundle\Manager\RegionConfigManager 
        arguments:
            entityManager:  @doctrine.orm.entity_manager
            translator:     @translator
